zookeeper:
  image: "wurstmeister/zookeeper"
  ports:
    - "2181"

kafka:
  image: "wurstmeister/kafka"
  ports:
    - "9092"
  links:
    - "zookeeper:zk"
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "172.17.42.1"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"

fanout:
  build: "."
  dockerfile: "./fanout/Dockerfile"
  ports:
    - "4987"
  links:
    - "kafka:kafka"

integration:
  build: "."
  dockerfile: "./integration/Dockerfile"
  links:
    - "kafka:kafka"
    - "fanout:fanout"
